spring:
  application:
    name: catalog-service

  profiles:
    active: local # 기본값은 로컬로 설정
    include: secret # secret.yml도 같이 로드

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

jwt:
  expiration:
    access: 3600000
    refresh: 1209600000