spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  datasource:
    # 운영 서버 DB 주소 (내부망)
    url: jdbc:mysql://mysql:3306/pstracker?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    # 운영 서버의 환경변수(.env)에서 가져옴
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  file:
    name: /var/log/pstracker/catalog-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 3

server:
  forward-headers-strategy: native

crawler:
  url: http://collector-service:5000/run

app:
  auth:
    cookie-secure: true
    redirect-uri: https://ps-signal.com