spring:
  application:
    name: catalog-service
  profiles:
    active: local # 기본값은 로컬로 설정
    include: secret # secret.yml도 같이 로드

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

jwt:
  expiration:
    access: 3600000
    refresh: 1209600000