spring:
  datasource:
    # [중요] 도커 호스트(localhost)의 3307 포트로 접속 -> 도커 내부 3306으로 연결됨
    url: jdbc:mysql://localhost:3307/pstracker?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # [중요] validate: DB 테이블과 자바 Entity가 일치하는지 검사만 함 (테이블 자동 생성 X)
      # 우리는 방금 Adminer로 테이블을 완벽하게 만들었으므로 'validate'가 정석입니다.
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

discord:
  webhook:
    url: https://discord.com/api/webhooks/1445670168645861487/FXE5N8WcoXRfMVGHTQZr9pkCSF_0-YAT98bWXSRNwZGQ43LZZM6Q7It9A8jgxZYqReE5

igdb:
  client-id: "prxma4t42rqkh826svln7s5wxfu2wq"
  client-secret: "p0vs0nv2pcz4591pg2fbutsn9py0y7"
  auth-url: "https://id.twitch.tv/oauth2/token"
  api-url: "https://api.igdb.com/v4"