version: '3.8'
services:
  # 1. Selenium Grid (ì›ê²© ë¸Œë¼ìš°ì €)
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: ps-tracker-browser
    shm_size: "512m" # ë¬¼ë¦¬ ë¨ 1GB í•œê³„ë¡œ ìœ ì§€ (í•„ìˆ˜)
    environment:
      - TZ=Asia/Seoul
    # deploy: ğŸ‘ˆ [ì‚­ì œ] CPU ì œí•œì„ í’€ì–´ì„œ ì„œë²„ ì„±ëŠ¥ì„ í’€ë¡œ ì“°ê²Œ í•¨
    #   resources:
    #     limits:
    #       cpus: '0.5'
    networks:
      - ps-network
    restart: no
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/wd/hub/status" ]
      interval: 5s
      timeout: 5s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 2. Python Collector (Hand)
  collector-service:
    build: ./apps/collector-service
    container_name: ps-tracker-collector
    environment:
      - TZ=Asia/Seoul
      - API_BASE_URL=http://10.0.0.161:8080
      - SELENIUM_URL=http://selenium-chrome:4444/wd/hub
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    depends_on:
      selenium-chrome:
        condition: service_healthy
    networks:
      - ps-network
    restart: no
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ps-network:
    driver: bridge